"use client";
import { useEffect, useRef, useState } from 'react';
import { Fish, Plus, Anchor, Move, Upload, Sparkles, LoaderCircle, Check, ImageIcon } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
type Catch = {id:string; name:string; date:string; x:number; y:number; image:string; source?:string; sample?:boolean};
const demo:Catch={id:'sample',name:'黑鯛 · 示範襟章',date:'',x:.52,y:.48,image:'/sample-fish.png',sample:true};
async function request(url:string,options?:RequestInit){const r=await fetch(url,options);if(!r.headers.get('content-type')?.includes('application/json'))throw Error('收藏室暫時連線唔到，請重新整理再試。');const data=await r.json() as {error?:string;items:Catch[];item:Catch;generationReady:boolean};if(!r.ok)throw Error(data.error||'暫時未能儲存，請再試一次。');return data;}
export default function Home(){
 const [items,setItems]=useState<Catch[]>([]),[open,setOpen]=useState(false),[file,setFile]=useState<File|null>(null),[photo,setPhoto]=useState(''),[name,setName]=useState(''),[date,setDate]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[ready,setReady]=useState<boolean|null>(null),[reveal,setReveal]=useState<Catch|null>(null),[detail,setDetail]=useState<Catch|null>(null),[saving,setSaving]=useState<string|null>(null),[loaded,setLoaded]=useState(false),[sample,setSample]=useState<Catch|null>(null);
 const board=useRef<HTMLDivElement>(null), drag=useRef<{item:Catch;startX:number;startY:number;moved:boolean}|null>(null), current=useRef(items), submitting=useRef(false);current.current=items;
 useEffect(()=>{setDate(new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Hong_Kong'}));request('/api/catches').then(d=>{setItems(d.items);setReady(d.generationReady);setLoaded(true)}).catch(e=>{setNotice(e.message);setLoaded(true)});},[]);
 useEffect(()=>{if(!file){setPhoto('');return;}const url=URL.createObjectURL(file);setPhoto(url);return()=>URL.revokeObjectURL(url)},[file]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'start_catch_upload',description:'Open the fish photo upload form; does not upload or generate a badge.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');setOpen(true);return {status:'upload_form_open'}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 function choose(f?:File){if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)){setError('請選擇 JPG、PNG 或 WebP 圖片。');return;}if(f.size>10*1024*1024){setError('圖片太大，請選擇 10 MB 以下嘅相片。');return;}setFile(f);setError('');}
 async function generate(){if(!file||submitting.current)return;submitting.current=true;setBusy(true);setError('');try{const body=new FormData();body.append('image',file);body.append('name',name.trim()||'我的漁獲');body.append('date',date);const d=await request('/api/catches',{method:'POST',body});setItems(i=>[...i,d.item]);setOpen(false);setReveal(d.item);setFile(null);setName('');setNotice('新襟章已儲存，拖到水松板上吧！');}catch(e){setError((e as Error).message)}finally{setBusy(false);submitting.current=false}}
 async function place(item:Catch,x:number,y:number){const next={...item,x:Math.max(0,Math.min(1,x)),y:Math.max(0,Math.min(1,y))};setReveal(null);if(item.sample){setSample(next);setNotice('呢枚係示範襟章，唔會計入你嘅收藏。');return;}setItems(all=>all.map(i=>i.id===item.id?next:i));setSaving(item.id);try{await request('/api/catches/'+item.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({x:next.x,y:next.y})});setNotice('位置已儲存。')}catch(e){setItems(all=>all.map(i=>i.id===item.id?item:i));setNotice((e as Error).message)}finally{setSaving(null)}}
 function position(e:React.PointerEvent){const b=board.current!.getBoundingClientRect();const w=window.innerWidth<700?112:150;return {x:Math.max(0,Math.min(1,(e.clientX-b.left-w/2)/(b.width-w))),y:Math.max(0,Math.min(1,(e.clientY-b.top-85)/(b.height-170)))}}
 function start(e:React.PointerEvent<HTMLButtonElement>,item:Catch){if(saving||e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={item,startX:e.clientX,startY:e.clientY,moved:false}}
 function moving(e:React.PointerEvent){if(!drag.current)return;if(Math.hypot(e.clientX-drag.current.startX,e.clientY-drag.current.startY)<5&&!drag.current.moved)return;drag.current.moved=true;if(reveal){(e.currentTarget as HTMLElement).style.transform=`translate(${e.clientX-drag.current.startX}px,${e.clientY-drag.current.startY}px)`;return;}const p=position(e),item={...drag.current.item,...p};if(item.sample)setSample(item);else setItems(all=>all.map(i=>i.id===item.id?item:i));}
 function end(e:React.PointerEvent){const d=drag.current;if(!d)return;drag.current=null;(e.currentTarget as HTMLElement).style.transform='';if(d.moved){const b=board.current!.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom){if(!reveal){if(d.item.sample)setSample(d.item);else setItems(all=>all.map(i=>i.id===d.item.id?d.item:i))}return;}const p=position(e);void place(d.item,p.x,p.y)}else if(!reveal)setDetail(d.item)}
 function badge(item:Catch,isReveal=false){return <button aria-label={`${item.name}，拖放移動或按方向鍵調整位置`} className={'catch '+(isReveal?'reveal-catch':'')} style={isReveal?undefined:{left:`calc(${item.x*100}% - ${item.x} * var(--badge-size))`,top:`calc(${item.y*100}% - ${item.y*170}px)`}} onPointerDown={e=>start(e,item)} onPointerMove={moving} onPointerUp={end} onPointerCancel={()=>{drag.current=null;if(item.sample)setSample(item);else setItems(all=>all.map(i=>i.id===item.id?item:i))}} onKeyDown={e=>{const dirs:Record<string,number[]>={ArrowLeft:[-.03,0],ArrowRight:[.03,0],ArrowUp:[0,-.03],ArrowDown:[0,.03]};if(dirs[e.key]){e.preventDefault();if(!saving)void place(item,item.x+dirs[e.key][0],item.y+dirs[e.key][1]);}else if(e.key==='Enter'||e.key===' '){e.preventDefault();isReveal?void place(item,.5,.45):setDetail(item)}}}><span className="enamel"><span className="badge-stars">✦ &nbsp; FISH CLUB &nbsp; ✦</span><img src={item.image} alt={item.name} draggable={false}/><span className="badge-bottom">釣 魚 日 和</span></span><span className="fish-label">{item.name}</span>{item.sample&&<small className="demo-caption">DEMO · 試拖放</small>}</button>}
 return <main className="club"><header className="masthead"><a href="/" className="brand"><span className="brandmark"><Fish size={28}/></span><span>釣魚日和<small>TSURI BIYORI · FISHING CLUB</small></span></a><span className="club-id">釣った思い出を、ひとつずつ。<br/><b>COLLECT MOMENTS, NOT JUST FISH.</b></span><span className="member"><Anchor size={16}/> 我的收藏室</span></header><section className="workspace"><div className="board-heading"><div><span className="eyebrow">THE CATCH COLLECTION / 001</span><h1>每一尾，都有故事<span>。</span></h1></div><div className="count"><strong>{String(items.length).padStart(2,'0')}</strong><span>枚襟章<br/>COLLECTED</span></div></div><div className="wood-frame"><div className="cork" ref={board}>{!items.length&&<article className="welcome-note"><div className="tape"/><h2>收藏第一尾。</h2><p>上載魚相，生成專屬襟章。</p><button className="text-button" onClick={()=>{setSample(null);setReveal({...demo})}}>試玩示範襟章 <Sparkles size={13}/></button></article>}{items.filter(i=>i.id!==reveal?.id).map(i=><div key={i.id}>{badge(i)}</div>)}{sample&&reveal?.id!=='sample'&&badge(sample)}<button type="button" className="board-add" aria-label="上載漁獲相片並生成魚形襟章" onClick={()=>setOpen(true)}><span className="board-add-icon"><Plus size={19}/></span><span><b>生成魚形襟章</b><small>上載漁獲相片</small></span></button></div></div><div className="underboard"><span><Move size={15}/> 拖一拖，放喺你鍾意嘅位置</span><span>{saving?'儲存中…':items.length?'位置自動儲存':'屬於你嘅小小魚類圖鑑'}</span></div><div className="notice" role="status">{notice||(!loaded?'讀取收藏中…':'')}</div></section><footer>MADE FOR THE JOY OF FISHING <span>一魚一會 · EST. 2026</span></footer>
 <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent className="upload-dialog" showCloseButton={!busy} onInteractOutside={e=>{if(busy)e.preventDefault()}}><span className="eyebrow">A NEW CATCH / 新しい出会い</span><DialogTitle className="dialog-heading">將今日嘅漁獲，變成收藏。</DialogTitle><DialogDescription>上載一張清楚嘅魚相，AI 會保留外形同花紋，重畫成日系像素魚仔。</DialogDescription><label className={'upload-zone '+(photo?'has-photo':'')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)choose(e.dataTransfer.files[0])}}>{photo?<img src={photo} alt="待生成嘅魚相"/>:<><Upload size={28}/><b>揀一張魚相，或者拖入嚟</b><small>JPG、PNG、WebP · 上限 10 MB</small></>}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>choose(e.target.files?.[0])}/>{photo&&<span className="change-photo">更換相片</span>}</label><div className="form-row"><label>魚名／暱稱<input value={name} maxLength={50} placeholder="例如：第一尾黑鯛" disabled={busy} onChange={e=>setName(e.target.value)}/></label><label>釣獲日期<input type="date" value={date} required disabled={busy} onChange={e=>setDate(e.target.value)}/></label></div>{ready===false&&<p className="setup-note">AI 生圖連線尚未設定。你可以先揀相，或者試玩示範襟章。</p>}{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={!file||!date||busy||ready===false} onClick={generate}>{busy?<LoaderCircle className="spin" size={18}/>:<Sparkles size={18}/>} {busy?'魚仔變身中…':'生成我的像素襟章'}</button>{busy&&<p className="waiting">好作品需要少少耐性，請保持視窗開啟。</p>}</DialogContent></Dialog>
 {reveal&&<div className="reveal-stage"><div className="reveal-copy"><span className="eyebrow">{reveal.sample?'TRY A LITTLE MAGIC':'NEW CATCH UNLOCKED!'}</span><h2>{reveal.sample?'試吓將佢放上板。':'新夥伴，入手！'}</h2><p>拖住襟章，放到水松板上。</p></div>{badge(reveal,true)}<button className="place-button" onClick={()=>void place(reveal,.5,.45)}><Check size={16}/> 放到板上</button></div>}
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null)}}><DialogContent className="upload-dialog"><DialogTitle>{detail?.name}</DialogTitle><DialogDescription>{detail?.sample?'示範襟章，未計入收藏。':`釣獲日期：${detail?.date}`}</DialogDescription>{detail&&<div className="detail-images"><img src={detail.image} alt="像素襟章魚仔"/>{detail.source&&<img src={detail.source} alt="原始漁獲照片"/>}</div>}<p className="waiting"><ImageIcon size={16}/> 一張相片，留低一個釣魚故事。</p></DialogContent></Dialog>
 </main>
}
